/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppProjectsIndexImport } from './routes/app/projects/index'
import { Route as AppProjectsProjectIdIndexImport } from './routes/app/projects/$projectId/index'
import { Route as AppProjectsProjectIdResultsResultIdImport } from './routes/app/projects/$projectId/results/$resultId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const AppProjectsIndexRoute = AppProjectsIndexImport.update({
  path: '/app/projects/',
  getParentRoute: () => rootRoute,
} as any)

const AppProjectsProjectIdIndexRoute = AppProjectsProjectIdIndexImport.update({
  path: '/app/projects/$projectId/',
  getParentRoute: () => rootRoute,
} as any)

const AppProjectsProjectIdResultsResultIdRoute =
  AppProjectsProjectIdResultsResultIdImport.update({
    path: '/app/projects/$projectId/results/$resultId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/projects/': {
      preLoaderRoute: typeof AppProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/projects/$projectId/': {
      preLoaderRoute: typeof AppProjectsProjectIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/projects/$projectId/results/$resultId': {
      preLoaderRoute: typeof AppProjectsProjectIdResultsResultIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppIndexRoute,
  AppProjectsIndexRoute,
  AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdResultsResultIdRoute,
])

/* prettier-ignore-end */
